version: '3.1'
services:
  web:
    image: node:8
    volumes:
      - '.:/usr/src/YOUR_PROJECT_NAME/'
    working_dir: /usr/src/YOUR_PROJECT_NAME
    command: npm run installstart
    ports:
      - '3000:4200'